<div class="container mx-auto max-w-prose py-8">
  <div class="flex flex-col">
    <h2 class="text-3xl text-left mb-2">What is it?</h2>
    <p class="text-xl text-justify mb-4">
      REDBUD was created to separate the registration process from the engine itself, while also speeding up the process of creating new elements, like entities, items, etc.
    </p>

    <h2 class="text-3xl text-left mt-4 mb-2">Why?</h2>
    <p class="text-xl text-justify mb-4">
      I decided to make it that way, because I hate defining game elements in code. Also, this approach allows for hot-reloading of the game elements WITHOUT recompiling! (Which is very good. Rust is amazing, but it takes some time to compile)
    </p>

    <p class="text-xl text-justify mb-4">
      The best thing? This is all zero-cost. Or well, it makes the game launch a little slower, but it is negligible. The advantages far outweigh the disadvantages.
    </p>

    <h2 class="text-3xl text-left mt-4 mb-2">How does it work?</h2>
    <p class="text-xl text-justify mb-4">
      Most game objects are composed of a .json and a .rs file, which are generated by the webapp. The .json file serves as the static data storage, like the maxHP, components that the element uses, etc. The .rs file is the actual code that is executed when the game runs. The code attaches itself to hooks like OnHit, OnSpawn, OnTick, you get the idea.
    </p>

    <h2 class="text-3xl text-left mt-4 mb-2">Additional details</h2>
    <p class="text-xl text-justify mb-4">
      To improve launch performance, the .json files are converted to .bson files as a sort of caching. If the corresponding .json files change at all, the .bson files are updated automatically on launch. That way, we don't sacrifice performance for human-redability.
    </p>

    <h2 class="text-3xl text-left mt-4 mb-2">Where should I start?</h2>
    <p class="text-xl text-justify">
      To begin using the webapp, create a new project and add some elements! I did my best to make it as intuitive as I could, but if you have any questions, I left some examples on github. There is also a tutorial explaining how to use the webapp.
    </p>
  </div>
</div>